### ISSUE TITLE
Mainnet Beat > Repay page > Issues Identified

### ISSUE THREAD

**Issue by renatco** [percent-finance/percent-dev#3]
Hitting the "Max" button inserts the wrong amount. 

Why shall I repay 109.9 USDC if my Borrow Balance is 9.9 USDC? 

I believe this "Max" button shall auto-insert THE SMALLEST OF two amounts - 
a) outstanding Borrow Balance 
OR 
b) amount of these tokens in my wallet. 

![image](https://user-images.githubusercontent.com/114657/94100443-aed47800-fdfb-11ea-9a04-bfcf83cb3bba.png)

**Comment by PercentFinance** [comment]
Thanks! You're right! The bug is now fixed.
